---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: minio-test-vks-int-vmar-se
  namespace: minio
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`minio.test.vks.int.vmar.se`)
    kind: Rule
    services:
    - name: minio-1606898619
      port: 9000
  tls:
    certResolver: default

