---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: minio-console
spec:
  selector:
    matchLabels:
      app: minio-console
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio-console
    spec:
      containers:
      - name: minio-console
        image: minio/console:v0.6.3
        args:
        - server
        env:
        - name: CONSOLE_PBKDF_PASSPHRASE
          valueFrom:
            secretKeyRef:
              name: minio-console-creds
              key: CONSOLE_PBKDF_PASSPHRASE
        - name: CONSOLE_PBKDF_SALT
          valueFrom:
            secretKeyRef:
              name: minio-console-creds
              key: CONSOLE_PBKDF_SALT
        - name: CONSOLE_MINIO_SERVER
          valueFrom:
            secretKeyRef:
              name: minio-console-creds
              key: CONSOLE_MINIO_SERVER
        ports:
        - containerPort: 9443
        - containerPort: 9090

