apiVersion: v1
kind: Secret
metadata:
  name: minio-console-vmar-creds
  namespace: minio
type: Opaque
stringData:
    CONSOLE_PBKDF_PASSPHRASE: "thisISsecret2017"
    CONSOLE_PBKDF_SALT: "SECRETsuperSECRETsuper1234"
    CONSOLE_ACCESS_KEY: "vmaradmin"
    CONSOLE_SECRET_KEY: "3k0pLugg3n"
    CONSOLE_MINIO_SERVER: "http://minio-vmar:9000"
